# Generated by Django 5.1.2 on 2024-12-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
